version: '3'
services:
    familyapp:
      build: ./familyapp
      ports:
      - "8081:8081"
      depends_on:
      - database
    familymemberapp:
      build: ./familymemberapp
      ports:
      - "8082:8082"
      depends_on:
      - familyApp
    database:
      container_name: "familyapp"
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD:
        MYSQL_USER: family_user
        MYSQL_PASSWORD:password
      ports:
      - "3306:3306"
      restart: always